why didn't this fail earlier then???

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,15 +25,15 @@ jobs:
 
     - name: Run container for testing
       run: |
-        docker run -d --name lolei-app-ci -p 5000:5000 lolei-app:ci
+        docker run -d --name lolei-app-ci -p 127.0.0.1:5000:5000 lolei-app:ci
 
         sleep 5
 
         RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
         echo "HTTP response code: $RESPONSE"
         if [ "$RESPONSE" -ne 200 ]; then
-        echo "Container test failed"
-        exit 1
+            echo "Container test failed"
+            exit 1
         fi
 
     - name: Stop container
