test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,11 +30,11 @@ jobs:
         sleep 5
 
         RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
-	echo "HTTP response code: $RESPONSE"
-	if [ "$RESPONSE" -ne 200 ]; then
-	   echo "Container test failed"
-	   exit 1
-	fi
+        echo "HTTP response code: $RESPONSE"
+        if [ "$RESPONSE" -ne 200 ]; then
+        echo "Container test failed"
+        exit 1
+        fi
 
     - name: Stop container
       run: |
